### ISSUE TITLE
Where is scotch_6.0.3?

### ISSUE THREAD

**Issue by cbcoutinho** [OpenFOAM/ThirdParty-2.4.x#1]
I had to copy the scotch directory from the ThirdParty 2.4.0 snapshot ([link](http://downloads.sourceforge.net/foam/ThirdParty-2.4.0.tgz?use_mirror=mesh)) and place it into my local git clone directory, which isn't ideal. Was this taken out and placed elsewhere?

**Comment by OpenFOAM** [comment]
Please upgrade to OpenFOAM-4.x or better still OpenFOAM-dev, scotch_6.0.3 is included in  ThirdParty for these versions and the corresponding deb-packs.
